//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuturno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalistasC
    {
        public int idAnalistasC { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
