//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuturno.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalistasM
    {
        public int idAnalistasM { get; set; }
        public string NombreCompleto1 { get; set; }
        public string NombreCompleto2 { get; set; }
        public int Turno { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
